version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DEBIAN_FRONTEND=noninteractive
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    command: /bin/bash /app/dbinit.sh && npm start

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
